name = "Shell-Jinja"
grammar = "jinja2"
path_suffixes = ["bash.jinja", "bash.jinja2", "bash.j2", "bashrc.jinja", "bashrc.jinja2", "bashrc.j2", "profile.jinja", "profile.jinja2", "profile.j2", "sh.jinja", "sh.jinja2", "sh.j2", "zsh.jinja", "zsh.jinja2", "zsh.j2", "zshrc.jinja", "zshrc.jinja2", "zshrc.j2"]
block_comment = ["{#", "#}"]
